name: finance_fantasy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  intl: ^0.20.2
  drift: ^2.27.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  fuzzy: ^0.5.1
  connectivity_plus: ^6.1.4
  worker_manager: ^7.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  test: ^1.25.0
  retrofit_generator: ^9.2.0
  drift_dev: ^2.27.0
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env
